### ISSUE TITLE
support for JSON files

### ISSUE THREAD

**Issue by LohithArcot** [Ezhvsalate/rasa-storyteller#2]
Can we have support for _JSON_ files. Now only _md_ file are supported.

**Comment by Ezhvsalate** [comment]
@lohithpro I think it is possible, I'll realize it when have some more free time.
You can also use conversion tool: https://rasa.com/docs/rasa/user-guide/command-line-interface/#convert-data-between-markdown-and-json

**Comment by Ezhvsalate** [comment]
@lohithpro in version 0.2.0 you can load data from any of nlu.md  / nlu.json files.
On export also both files will be generated so you can choose which one you need.

**Comment by LohithArcot** [comment]
@Ezhvsalate Is there a bug? The installation isn't successful! I got the below error.   
` UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 805: character maps to <undefined>` Should the `encoding` parameter be added? to `open` function?

**Comment by Ezhvsalate** [comment]
@lohithpro please attach full stacktrace of an error. I tested with files containing cyrillic characters and it worked fine.
Also checked all `open(...` places in code - everywhere I see something like `with open(..., "w", encoding="utf-8")`

**Comment by LohithArcot** [comment]
@Ezhvsalate  just to remove any possible system related errors. I tried the same on two windows systems. Here is the Traceback.

```
C:\Users\******>pip install rasa-storyteller
Collecting rasa-storyteller
  Downloading rasa-storyteller-0.2.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\******\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\******\\AppData\\Local\\Temp\\pip-install-2wc5ol8m\\rasa-storyteller\\setup.py'"'"'; __file__='"'"'C:\\Users\\******\\AppData\\Local\\Temp\\pip-install-2wc5ol8m\\rasa-storyteller\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\******\AppData\Local\Temp\pip-pip-egg-info-cjjefadz'
         cwd: C:\Users\******\AppData\Local\Temp\pip-install-2wc5ol8m\rasa-storyteller\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\******\AppData\Local\Temp\pip-install-2wc5ol8m\rasa-storyteller\setup.py", line 4, in <module>
        long_description = f.read()
      File "c:\users\******\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 805: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Ezhvsalate** [comment]
@lohithpro thanks for reporting, could reproduce it on win10 system. 
Released a quickfix, please try installing v0.2.1
